### ISSUE TITLE
读取数据问题

### ISSUE THREAD

**Issue by hai0shen** [xuuhaoo/OkSocket#104]
作者是把一次接收到多包数据的时候进行处理完一包就把后面的丢弃了是吗？而不是把后面接上来的进行不断拼包处理

**Comment by hai0shen** [comment]
如果长时间断开没有连接的话会出现这个错误


2018-10-06 11:21:06.190 29927-29946/com.zx.sdl E/AndroidRuntime: FATAL EXCEPTION: dispatch_thread
    Process: com.zx.sdl, PID: 29927
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.xuhao.android.libsocket.impl.client.action.ActionDispatcher.handleMessage(ActionDispatcher.java:264)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by xuuhaoo** [comment]
框架主要处理的就是粘包拆包 也就你说的断包

**Comment by hai0shen** [comment]
测试了多遍设置了setCallbackInThread(true)后会报上述说的错误
设置为false测试暂时还没有报以上错误。

**Comment by xuuhaoo** [comment]
好的...这个问题我重现下..谢谢反馈

**Comment by xuuhaoo** [comment]
Thank you for your reporting the bug of java.util.ConcurrentModificationException.
We already fix that in version 3.1.1.
Please update your dependency of OkSocket Library.
Tks again.
