### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by elli0tk** [xuuhaoo/OkSocket#147]
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x75831f50 self=0xe6f6a000
  | sysTid=20267 nice=0 cgrp=default sched=0/0 handle=0xeb6d3494
  | state=S schedstat=( 89101052741 20934631664 154184 ) utm=7365 stm=1544 core=3 HZ=100
  | stack=0xff7ba000-0xff7bc000 stackSize=8MB
  | held mutexes=
  at z.coz.a(ConnectionManagerImpl.java:232)
  - waiting to lock <0x03fcc6c8> (a z.coz) held by thread 26
  at z.cpe.b(ActionHandler.java:60)
  at z.cpd.a(ActionDispatcher.java:114)
  at z.cpd.a(ActionDispatcher.java:37)
  at z.cpd$b.run(ActionDispatcher.java:283)
  - locked <0x0de1c361> (a java.util.ArrayList)
  at android.os.Handler.handleCallback(Handler.java:907)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:216)
  at android.app.ActivityThread.main(ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by xuuhaoo** [comment]
已经在master分支修了,因为还没有验证过,因此需要你源码依赖,验证之后才会发版
