### ISSUE TITLE
作者你好,使用okSocket发生java.nio.BufferOverflowException 异常问题

### ISSUE THREAD

**Issue by zhouke23** [xuuhaoo/OkSocket#48]
作者大大 你好, 最近发现在使用的时候 发生缓冲 异常问题: 不知道应该怎么解决,来请教一下!
com.xuhao.android.libsocket.impl.exceptions.ReadException: java.nio.BufferOverflowException
    at com.xuhao.android.libsocket.impl.blockio.io.Reader.read(Reader.java:105)
    at com.xuhao.android.libsocket.impl.blockio.threads.DuplexReadThread.runInLoopThread(DuplexReadThread.java:35)
    at com.xuhao.android.libsocket.impl.LoopThread.run(LoopThread.java:50)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.nio.BufferOverflowException
    at java.nio.Buffer.checkPutBounds(Buffer.java:183)
    at java.nio.ByteArrayBuffer.put(ByteArrayBuffer.java:266)
    at com.xuhao.android.libsocket.impl.blockio.io.Reader.readBodyFromChannel(Reader.java:126)
    at com.xuhao.android.libsocket.impl.blockio.io.Reader.read(Reader.java:94)

**Comment by zhouke23** [comment]
找到原因是 出至  Reader 类 ,  readBodyFromChannel方法 当 if (len > remaining)  为 false 的时候!
但是我不知道怎么解决了!

**Comment by zhouke23** [comment]
具体操作是这样的,大约1.5s内的 频繁的调用socket 发送协议! 然后不知道为什么read接收时突然就报异常了~

**Comment by xuuhaoo** [comment]
使用最新版本吧,最新版本没有Reader这个类了1.2.3
