### ISSUE TITLE
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuange.filling/com.yuange.filling.Activity.MainSimpleActivity}: java.lang.RuntimeException: 上下文不能为空

### ISSUE THREAD

**Issue by WZRRRRRR** [xuuhaoo/OkSocket#64]
请问这个是什么情况
initData();方法中的  mManager = open(mInfo, mOkOptions);这句报错 在demo程序中运行就报错,但是我写到我的程序里就这句报错

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuange.filling/com.yuange.filling.Activity.MainSimpleActivity}: java.lang.RuntimeException: 上下文不能为空
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                     Caused by: java.lang.RuntimeException: 上下文不能为空
                                                                        at com.xuhao.android.libsocket.sdk.OkSocket.assertIsInit(OkSocket.java:82)
                                                                        at com.xuhao.android.libsocket.sdk.OkSocket.open(OkSocket.java:56)
                                                                        at com.yuange.filling.Activity.MainSimpleActivity.initData(MainSimpleActivity.java:87)
                                                                        at com.yuange.filling.Activity.MainSimpleActivity.onCreate(MainSimpleActivity.java:60)
                                                                        at android.app.Activity.performCreate(Activity.java:6303)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by xuuhaoo** [comment]
请在Application中进行初始化

**Comment by WZRRRRRR** [comment]
好的,我的锅....

**Comment by WZRRRRRR** [comment]
谢谢啦
